# Generated by Django 4.1.2 on 2023-04-20 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_roommodel_total_rooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporalBookingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('total_price', models.IntegerField()),
                ('total_guests', models.IntegerField()),
                ('entitled_guest_name', models.CharField(max_length=20)),
                ('entitled_guest_surname', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('expires_at', models.DateTimeField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporal_bookings', to='core.roommodel')),
            ],
        ),
    ]
