# Generated by Django 4.1.2 on 2023-05-11 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_temporalbookingmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PicturesPlacesModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures_places', to='core.placemodel')),
            ],
        ),
    ]
